// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WywozSmieci.Database;

namespace WywozSmieci.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200817154716_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("WywozSmieci.Model.Rejon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Miejsce")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rejons");
                });

            modelBuilder.Entity("WywozSmieci.Model.Wywoz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Typ")
                        .HasColumnType("TEXT");

                    b.Property<int?>("rejonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("rejonId");

                    b.ToTable("Wywozs");
                });

            modelBuilder.Entity("WywozSmieci.Model.Wywoz", b =>
                {
                    b.HasOne("WywozSmieci.Model.Rejon", "rejon")
                        .WithMany()
                        .HasForeignKey("rejonId");
                });
#pragma warning restore 612, 618
        }
    }
}
